### ISSUE TITLE
Export internal functions

### ISSUE THREAD

**Issue by cstich** [rahmarid/stablespec#2]
What about exposing `optimalModels`, `structureStab`, `relevantStructure` to the user? If you do that, a user can call `optimalModels` independently on whatever computation platform she wants and then could later stitch the models together manually? In fact that is my exact use case right now.

**Comment by rahmarid** [comment]
That might be a good idea. I need to check all of them again though, to make sure they are readable enough.

**Comment by cstich** [comment]
Cool.
