### ISSUE TITLE
Subscript out of bounds?

### ISSUE THREAD

**Issue by guhjy** [rahmarid/stablespec#3]
The problem occurs every time I increase the elements of the consMatrix to more than 15:

> the_data <- crossdata6V
> numSubset <- 1
> num_iteration <- 5
> num_pop <- 10
> mut_rate <- 0.075
> cross_rate <- 0.85
> longi <- FALSE
> num_time <- 1
> the_seed <- NULL
> the_co <- "covariance"
> #assummed that variable 5 does not cause variables 1, 2, and 3
> cons_matrix <- matrix(c(2,1, 3,1, 4,1, 5,1,  3,2,4,2, 5,2, 6,2, 4,3, 5,3,  1,4, 2,4, 3,4, 5,4,  1,5, 2,5), 16, 2, byrow=TRUE)
> th <- 0.1
> to_plot <- FALSE
> mix <- FALSE
> 
> result <- stableSpec(theData=the_data, nSubset=numSubset, iteration=num_iteration, nPop=num_pop, mutRate=mut_rate, crossRate=cross_rate, longitudinal=longi, numTime=num_time, seed=the_seed, co=the_co, consMatrix=cons_matrix, threshold=th, toPlot=to_plot, mixture = mix)

Error in { : task 1 failed - "subscript out of bounds"

**Comment by rahmarid** [comment]
Thanks for pointing this out. The problem is in the initialPopulation() where you have more constraints than the number of models, ie., when initially feeding the population with a model from each model complexity. I fixed the bug, the current version should work properly w.r.t to the problem.
